version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily

    groups:
      framework-updates:
        patterns:
          - "express"
          - "@azure/*"

    open-pull-requests-limit: 5
